server:
  port: 44401
  servlet:
    context-path: /demo

spring:
  dubbo:
    application:
      name: spring-boot-demo-dubbo-consumer
#      registry: zookeeper://127.0.0.1:2181
      registry: zookeeper://192.168.31.214:2181


project:
  name: ${spring.dubbo.application.name}
csp:



